name: Run Unit Tests on PR

permissions:
  pull-requests: write
  contents: read

on: 
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.14.0'

    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      run: npm test -- --config package.json

    - name: PR Comment - Tests Finished
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        message: "Testy zakończone!"
